### ISSUE TITLE
shadowColor is not working

### ISSUE THREAD

**Issue by kotoyama** [dotmind/rn-shadow-generator#3]
Hi, thanks for your work!
I applied color to `shadowColor` property, and nothing changes. `'red'`, `'#2C66F5'`, `'rgba(0, 0, 0, 0.1)'` - no matter what I tried, nothing worked.
Tested on Android 8, RN 0.64.1, latest library version.

**Comment by anthlasserre** [comment]
Hey @kotoyama 👋🏼 
Can you post here a preview of the component you're using `shadowColor` ?
To be able to reproduce and debug quickly.

Thanks
